Uncomment code that seems to be causing issues, when running on Scicore.
* I got this error message on Scicore:

[micuby52@worker04 logs]$ ml Python/3.7.3-foss-2018b
(venv-testenv) [micuby52@worker04 logs]$ python "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable/Preproc/call_preproc_fun.py"   -i "/scicore/home/nimwegen/GROUP/MM_Data/Dany/20190424/20190424_hi2_hi3_med2
_rplN_glu_gly/20190424_hi2_hi3_med2_rplN_4/"   -o "/scicore/home/nimwegen/GROUP/Moma/MM_Testing/10_20190424_hi2_hi3_med2_rplN_glu_gly/output" -p Pos0 -r 180 -ff /scicore/home/nimwegen/GROUP/MM_Data/Dany/20190424
/20190424_flatfieldGFP_3/ -tmax 10
Traceback (most recent call last):
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable/Preproc/call_preproc_fun.py", line 15, in <module>
    from mmpreprocesspy.preproc_fun import preproc_fun
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/mmpreprocesspy/mmpreprocesspy/preproc_fun.py", line 13, in <module>
    from mmpreprocesspy.moma_image_processing import MomaImageProcessor
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/mmpreprocesspy/mmpreprocesspy/moma_image_processing.py", line 2, in <module>
    from mmpreprocesspy import preprocessing
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/mmpreprocesspy/mmpreprocesspy/preprocessing.py", line 2, in <module>
    import mmpreprocesspy.dev_auxiliary_functions as aux
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/mmpreprocesspy/mmpreprocesspy/dev_auxiliary_functions.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/venv-testenv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/venv-testenv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/venv-testenv/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/venv-testenv/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'