Comment out usages of matplot, which cause an exception when running without tk or graphic interface.
* See here for discussion: https://github.com/matplotlib/matplotlib/issues/9017#issuecomment-321684727
* One can also work around this using by setting a text-based matplotlib backend like so:
    import matplotlib
    matplotlib.use('agg')
* Error message is like so:
  File "/home/micha/Documents/git/mmpreprocesspy/venv-testenv/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
ModuleNotFoundError: No module named 'tkinter'