Fix tifffile package version to 2020.10.1: The new version is causing issues a dataset.
This is the problematic dataset (see error message below):
/scicore/home/nimwegen/GROUP/MM_Data/Dany/20190515/20211103_preprocessing_michael/new_mmpreproc_version

Working:
(/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211027__FOR_PREPROCESSING_ONLY__mmpreprocesspy__7fa33bda/mmpreprocesspy_conda_environment) micuby52@worker04 moma (dev)$ conda list | grep tifffile
tifffile                  2020.10.1        py37hdd07704_2

Not working:
(/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/mmpreprocesspy_conda_environment) micuby52@worker04 moma (dev)$ conda list | grep tifffile
tifffile                  2021.7.2           pyhd3eb1b0_2

This is the error message:
back (most recent call last):
  File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/Preproc/call_preproc_fun.py", line 118, in <module>
      image_registration_method=args.image_registration_method)
        File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/mmpreprocesspy/mmpreprocesspy/preproc_fun.py", line 119, in preproc_fun
            dataset = MicroManagerOmeTiffReader(data_folder)
              File "/scicore/home/nimwegen/GROUP/Moma/MM_Setup/git_repos_unstable/mmpreprocesspy/mmpreprocesspy/mmpreprocesspy/MicroManagerOmeTiffReader.py", line 22, in __init__
                  for position in self.tiff.series:
                    File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/mmpreprocesspy_conda_environment/lib/python3.7/site-packages/tifffile/tifffile.py", line 1001, in __get__
                        value = self.func(instance)
                          File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/mmpreprocesspy_conda_environment/lib/python3.7/site-packages/tifffile/tifffile.py", line 3314, in series
                              if getattr(self, 'is_' + name, False):
                                File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/mmpreprocesspy_conda_environment/lib/python3.7/site-packages/tifffile/tifffile.py", line 4670, in __getattr__
                                    value = bool(getattr(self.pages[0], name))
                                      File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/mmpreprocesspy_conda_environment/lib/python3.7/site-packages/tifffile/tifffile.py", line 1001, in __get__
                                          value = self.func(instance)
                                            File "/scicore/home/nimwegen/GROUP/Moma/MM_Analysis/unstable_20211104__FOR_PREPROCESSING_ONLY__mmpreprocesspy_8cd4f70d/mmpreprocesspy_conda_environment/lib/python3.7/site-packages/tifffile/tifffile.py", line 7136, in is_shaped
                                                if not description or '"mibi.' in description:
                                                TypeError: a bytes-like object is required, not 'str'Please enter the commit message for your changes. Lines starting